### ISSUE TITLE
No code present!

### ISSUE THREAD

**Issue by ShivamHP** [srn08/asanaApp#1]
You might have forgotten to add all files to the repo.  
  
You would have done something like this:  
```
git add README.md
```
Instead, write this code:  
```
git add *
```

Info: * is an escape character which means "everything". So if you write git add *, everything in the current directory would be marked to be added to remote.

**Comment by srn08** [comment]
there are 2 branches, open master branch, there you will find the code. For some reason i cannot pull master onto the main branch

**Comment by ShivamHP** [comment]
Follow these commands: [How to change branch on Git terminal](https://devconnected.com/how-to-switch-branch-on-git/). 

If you are not unable to do it even after going through this, then you can contact your DevSoc mentor
